replicaCount: 1

image:
  repository: localhost:5001/sample-app

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

ingress:
  enabled: true
  hosts:
    - host: sample-app.local
      paths:
        - path: /
          pathType: Prefix

hpa:
  enabled: false

pdb:
  enabled: false

networkPolicy:
  enabled: false
